import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SessionWrapper from "@/components/session/SessionWrapper";
import Container from "@/components/ui/Container";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <NextTopLoader color="gray" />
          <Navbar />
          <Container>
            {children}
            <Toaster richColors theme="dark" />
          </Container>
        </SessionWrapper>
      </body>
    </html>
  );
}
